### PR TITLE
Hide magic attributes in CVMFS configuration of EESSI containers + update to CernVM-FS 2.9.4

### PR DESCRIPTION
**Pull request by bedroge**
See #110. Also bumped the version of CVMFS to 2.9.4.

### CODE REVIEW

**Review by ocaisa — APPROVED** [review]
LGTM

**Comment by bedroge** [comment]
Oh, right, I have to spin up our VM with self-hosted runners for some actions...

**Comment by bedroge** [comment]
Not sure why that check is failing, will check again after my vacation.

**Comment by ocaisa** [comment]
Should we consider adding this setting to the [recommended configuration in the README](https://github.com/EESSI/filesystem-layer/blame/main/README.md#L183)...and are there other places we should inject it?

**Comment by bedroge** [comment]
> Should we consider adding this setting to the [recommended configuration in the README](https://github.com/EESSI/filesystem-layer/blame/main/README.md#L183)...and are there other places we should inject it?

That probably makes sense, let's add that to issue #110?

I've fixed the container builds on `ppc64le`. Also included a fix for the client containers, which had a broken `fuse-overlayfs` (it was building a binary, but then it also tried to download a non-existing binary, which resulted in a file containing `404 not found`).

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
