### PR TITLE
Fix typo in build-client-packages

### PR DESCRIPTION
**Pull request by peterstol**
Small typo in the filename.

### CODE REVIEW

**Review by bedroge — APPROVED** [review]
Thanks for spotting this! :-)

**Comment by boegel** [comment]
Ouch. @bedroge we should tag a 0.2.1 so we get new packages to download?

**Comment by bedroge** [comment]
We can just do what everyone else does and rerelease 0.2.0? ;-)

But I was planning to release 0.2.1 after the other PR got merged, so that there's at least something new :-)

**Comment by boegel** [comment]
It crossed my mind, but then I slapped myself to snap out of it really quickly. ;)

#40 is merged!

**Pull request merged**
