### PR TITLE
added ansible requirements.yml and update README

### PR DESCRIPTION
**Pull request by pescobar**
The "ansible way" to define dependency roles is to use `ansible-galaxy` with a `requirements.yml`. This way you don't need to worry about git-submodules and mainly you improve reproducibility because you can fix which version of the role you are using instead of pointing to master.

Another possible improvement for reproducibility could be to provide a pip `requirements.txt` which defines the specific ansible and python libraries that are tested to run the playbook but that's probably something for a different PR in case you are interested.

### CODE REVIEW

**Comment by bedroge** [comment]
I'll try to test this tomorrow. Since we renamed the name of the galaxyproject.cvmfs role to just cvmfs in our git submodule, we also have to change this back to galaxyproject.cvmfs in all the different playbooks.

**Comment by pescobar** [comment]
good point, I missed that. I will try to update the PR

**Comment by bedroge** [comment]
Thanks @pescobar! I've just tested all the playbooks on clean VMs, and everything still seems to work fine.

**Comment by pescobar** [comment]
@bedroge  if you test the playbook using VMs maybe you are interested on the vagrant file I have in this repo https://github.com/pescobar/ansible-beegfs-vagrant-tests

**Comment by bedroge** [comment]
@pescobar Might be useful, thanks!

**Pull request merged**
